// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // fallback to web for Windows
      case TargetPlatform.linux:
        return web; // fallback to web for Linux
      default:
        return windows;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkY4Ax_cpbHZnDcM5hMbemyydo1AwZsY',
    appId: '1:444257486007:web:7fe54d56a994424396f932',
    messagingSenderId: '444257486007',
    projectId: 'triplix-ai',
    authDomain: 'triplix-ai.firebaseapp.com',
    storageBucket: 'triplix-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6hU858PM84_88pNbBrb3_JmhE2XjmeA',
    appId: '1:444257486007:android:fcc35b045149410796f932',
    messagingSenderId: '444257486007',
    projectId: 'triplix-ai',
    storageBucket: 'triplix-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAALFmznubu3-rYgZCJeNGiidGS0dVtkWQ',
    appId: '1:444257486007:ios:0e120520afa6389596f932',
    messagingSenderId: '444257486007',
    projectId: 'triplix-ai',
    storageBucket: 'triplix-ai.firebasestorage.app',
    iosClientId: '444257486007-5fado9d54tjes3r67kp5dcei1f88qj4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAALFmznubu3-rYgZCJeNGiidGS0dVtkWQ',
    appId: '1:444257486007:ios:0e120520afa6389596f932',
    messagingSenderId: '444257486007',
    projectId: 'triplix-ai',
    storageBucket: 'triplix-ai.firebasestorage.app',
    iosClientId: '444257486007-5fado9d54tjes3r67kp5dcei1f88qj4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmkY4Ax_cpbHZnDcM5hMbemyydo1AwZsY',
    appId: '1:444257486007:web:d3cc5050a3e425d796f932',
    messagingSenderId: '444257486007',
    projectId: 'triplix-ai',
    authDomain: 'triplix-ai.firebaseapp.com',
    storageBucket: 'triplix-ai.firebasestorage.app',
  );
}
