// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // fallback to web for Windows
      case TargetPlatform.linux:
        return web; // fallback to web for Linux
      default:
        return windows;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABpbx_kAtJ7rwcZ0uONIUoebgOvEmNIXM',
    appId: '1:966084332372:web:53c3883b85e4b4504756c1',
    messagingSenderId: '966084332372',
    projectId: 'triplix-831cc',
    authDomain: 'triplix-831cc.firebaseapp.com',
    storageBucket: 'triplix-831cc.firebasestorage.app',
    measurementId: 'G-L1BQQHZS66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkl_3cuB3eFKoy6wPjqVJARlJXCGhrTr0',
    appId: '1:966084332372:android:9c9c02ff8b4e1fc54756c1',
    messagingSenderId: '966084332372',
    projectId: 'triplix-831cc',
    storageBucket: 'triplix-831cc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVX1mHaWq9lzVbctOO6_RTyn1fBV3uvCg',
    appId: '1:966084332372:ios:d300eca0c36023fa4756c1',
    messagingSenderId: '966084332372',
    projectId: 'triplix-831cc',
    storageBucket: 'triplix-831cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterTravelApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVX1mHaWq9lzVbctOO6_RTyn1fBV3uvCg',
    appId: '1:966084332372:ios:d300eca0c36023fa4756c1',
    messagingSenderId: '966084332372',
    projectId: 'triplix-831cc',
    storageBucket: 'triplix-831cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABpbx_kAtJ7rwcZ0uONIUoebgOvEmNIXM',
    appId: '1:966084332372:web:c2f2c9cc868212674756c1',
    messagingSenderId: '966084332372',
    projectId: 'triplix-831cc',
    authDomain: 'triplix-831cc.firebaseapp.com',
    storageBucket: 'triplix-831cc.firebasestorage.app',
    measurementId: 'G-K62LB1N6EH',
  );
}
